[package]
name = "nate-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
nate = { path = "../nate" }
anyhow = { version = "1", features = ["backtrace"] }
memmap2 = "0"
elf = "0"
byteorder = "1"
tracing-subscriber = "0"
